version: '3.8'

services:
  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: opensearch-node
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9600:9600"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.0
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    depends_on:
      opensearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - opensearch-net

  python-app:
    build: .
    container_name: opensearch-python-app
    depends_on:
      opensearch:
        condition: service_healthy
      opensearch-dashboards:
        condition: service_healthy
    networks:
      - opensearch-net
    environment:
      - OPENSEARCH_HOST=opensearch
      - OPENSEARCH_PORT=9200
    volumes:
      - ./logs:/app/logs
    command: >
      sh -c "
        export PYTHONPATH=.
        echo 'Running prediction data script...' &&
        uv run src/db/save_prediction.py &&
        tail -f /dev/null
      "

  fastapi-server:
    build: .
    container_name: fastapi-server
    depends_on:
      opensearch:
        condition: service_healthy
      python-app:
        condition: service_started
    networks:
      - opensearch-net
    environment:
      - OPENSEARCH_HOST=opensearch
      - OPENSEARCH_PORT=9200
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    command: >
      sh -c "
        export PYTHONPATH=.
        echo 'Starting FastAPI server...'
        uv run uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
      "
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  opensearch-net:
    driver: bridge
